### ISSUE TITLE
Couldn't load plugin Video_UAV_Tracker due to an error when calling its classFactory method 

### ISSUE THREAD

**Issue by PedroVenancio** [sagost/Video_UAV_Tracker-3D#2]
Dear Salvatore,

I'm getting this python error in Video UAV Tracker since a few days ago.

```
Couldn't load plugin 'Video_UAV_Tracker' due to an error when calling its classFactory() method 

TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/PedroVenancio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Video_UAV_Tracker\__init__.py", line 46, in classFactory
    from .VideoGis import VideoGis
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/PedroVenancio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Video_UAV_Tracker\VideoGis.py", line 52, in 
    import resources
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/PedroVenancio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\resources.py", line 1251, in 
    qInitResources()
  File "C:/Users/PedroVenancio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\resources.py", line 1243, in qInitResources
    qt_resource_name, qt_resource_data)
TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'
```

This happen both in QGIS 3.4.12, 3.8.3 and master. Tested only in Windows.

**Comment by Jerome-Albaret** [comment]
I have the same problem. It's a pity because I really appreciate this plugin to view videos obtained with a GoPro.

**Comment by samaritakis** [comment]
Me too! Did you find any solution?

**Comment by kekaoliveira** [comment]
conseguiram resolver?

**Comment by kekaoliveira** [comment]
resolveram ?
